### ISSUE TITLE
Upstream SSL

### ISSUE THREAD

**Issue by torrybr** [werniq/forwarding-proxy#1]
It would be cool if the proxy was able to connect to upstream service via .p12 certificate aka mutual authentication support.  Similar to [ghostunnel](https://github.com/ghostunnel/ghostunnel) client mode but simpler and more config options like no verify on the certificate for dev purposes

**Comment by werniq** [comment]
Thank you!
I'm still developing in this area, so I'll google all the terms first, and then I'll start thinking about the implementation :))
